project_name: rpi-net-manager

version: 2

release:
  github:
    owner: TheCacophonyProject
    name: rpi-net-manager
  name_template: '{{.Tag}}'

builds:
- id: "rpi-net-manager"
  binary: "rpi-net-manager"
  main: "./cmd/rpi-net-manager"
  goos:
  - linux
  goarch:
  - arm64
  goarm:
  - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Network manager for Cacophony Raspberry Pi devices
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  contents:
    - src: _release/rpi-net-manager.service
      dst: /etc/systemd/system/rpi-net-manager.service
    - src: _release/org.cacophony.RPiNetManager.conf
      dst: /etc/dbus-1/system.d/org.cacophony.RPiNetManager.conf
    - src: _release/10-notify-rpi-net-manager
      dst: /lib/dhcpcd/dhcpcd-hooks/10-rpi-net-manager
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
